
import { NewsArticle, NewsCategory, Sentiment, UserRole, SocialMediaPost, SocialMediaPlatform } from './types';

export const GEMINI_MODEL_NAME = 'gemini-2.5-flash';

export const MOCK_CLIENTS: string[] = ['Cliente A', 'Cliente B', 'Cliente C', 'Instituições Públicas', 'Personalidades', 'Empresas de Tecnologia'];

export const MOCK_NEWS_ARTICLES: NewsArticle[] = [
  {
    id: '1',
    title: 'Cliente A Expande Participação de Mercado com Nova Aquisição',
    summary: 'A Cliente A anunciou uma aquisição estratégica que deve impulsionar significativamente sua participação no setor de tecnologia.',
    imageUrl: 'https://picsum.photos/600/400?random=1',
    source: 'Tech Daily',
    date: '2024-07-20T10:00:00Z',
    journalist: 'Jane Doe',
    category: NewsCategory.BUSINESS,
    client: 'Cliente A',
    sentiment: Sentiment.UNCLASSIFIED,
    link: 'https://example.com/client-a-acquisition',
    fullContent: 'A Cliente A, líder no setor de software empresarial, finalizou a aquisição da Startup Inovadora X, uma empresa especializada em soluções de IA para otimização de processos. Esta movimentação estratégica visa fortalecer a posição da Cliente A no mercado, diversificar seu portfólio de produtos e integrar tecnologias emergentes para oferecer um valor ainda maior aos seus clientes. Analistas de mercado veem a aquisição como um passo ousado e promissor para a expansão da empresa, com projeções de crescimento de 15% na receita no próximo trimestre. A integração das equipes e tecnologias deve ser concluída até o final do ano fiscal. Esta notícia é geralmente vista como positiva para o valor das ações da Cliente A e para o setor tecnológico como um todo.',
  },
  {
    id: '2',
    title: 'Nova Iniciativa Política Lançada por Instituição Pública',
    summary: 'Uma instituição pública revelou uma nova política destinada a melhorar a infraestrutura urbana, recebendo reações mistas do público.',
    imageUrl: 'https://picsum.photos/600/400?random=2',
    source: 'Gazeta Governamental',
    date: '2024-07-19T14:30:00Z',
    journalist: 'João Silva',
    category: NewsCategory.POLITICS,
    client: 'Instituições Públicas',
    sentiment: Sentiment.UNCLASSIFIED,
    link: 'https://example.com/public-policy',
    fullContent: 'O Ministério do Desenvolvimento Urbano anunciou hoje um plano ambicioso de revitalização de centros urbanos, com foco em transporte público e áreas verdes. Embora a iniciativa prometa melhorias significativas na qualidade de vida dos cidadãos, críticos apontam para a falta de detalhes sobre o financiamento e possíveis impactos no orçamento local. As reações iniciais do público são divididas, com alguns expressando otimismo cauteloso e outros preocupações com a execução e a transparência. Audiências públicas estão previstas para as próximas semanas para debater a proposta.',
  },
  {
    id: '3',
    title: 'Cliente B Apresenta Avanço em Energia Sustentável',
    summary: 'A Cliente B está na vanguarda da energia sustentável com seu mais recente avanço tecnológico, prometendo um futuro mais verde.',
    imageUrl: 'https://picsum.photos/600/400?random=3',
    source: 'Semana da Tecnologia Verde',
    date: '2024-07-18T09:15:00Z',
    journalist: 'Alice Castanho',
    category: NewsCategory.TECHNOLOGY,
    client: 'Cliente B',
    sentiment: Sentiment.UNCLASSIFIED,
    link: 'https://example.com/client-b-energy',
    fullContent: 'A Cliente B, uma empresa de energia renovável, divulgou hoje a patente de uma nova tecnologia de painéis solares com 25% mais eficiência que os modelos atuais. Este avanço representa um marco na busca por fontes de energia limpa e tem o potencial de revolucionar o mercado. Especialistas em energia comemoraram a notícia, destacando o impacto positivo na redução das emissões de carbono e na acessibilidade da energia solar. A expectativa é que os novos painéis estejam disponíveis comercialmente em até dois anos.',
  },
  {
    id: '4',
    title: 'Personalidade Local Reconhecida por Serviço Comunitário',
    summary: 'Uma proeminente personalidade local foi homenageada por suas extensas contribuições em várias iniciativas de serviço comunitário.',
    imageUrl: 'https://picsum.photos/600/400?random=4',
    source: 'Notícias da Cidade',
    date: '2024-07-17T11:00:00Z',
    journalist: 'Roberto Verde',
    category: NewsCategory.GENERAL,
    client: 'Personalidades',
    sentiment: Sentiment.UNCLASSIFIED,
    link: 'https://example.com/community-service',
    fullContent: 'Dona Maria, conhecida por seu trabalho voluntário incansável, recebeu ontem a "Medalha Cidadão Exemplar" em cerimônia municipal. Sua dedicação à causa dos desabrigados e à educação infantil foi destacada pelas autoridades. A comunidade expressou gratidão e admiração pelo legado de Dona Maria, que serve de inspiração para todos. Um evento beneficente está sendo organizado em sua homenagem no próximo mês.',
  },
  {
    id: '5',
    title: 'Cliente C Enfrenta Desafios no Relatório de Ganhos do Q2',
    summary: 'A Cliente C reportou ganhos abaixo do esperado para o segundo trimestre, resultando em uma queda no preço das ações.',
    imageUrl: 'https://picsum.photos/600/400?random=5',
    source: 'Financial Times',
    date: '2024-07-16T16:45:00Z',
    journalist: 'Sara Branco',
    category: NewsCategory.BUSINESS,
    client: 'Cliente C',
    sentiment: Sentiment.UNCLASSIFIED,
    link: 'https://example.com/client-c-earnings',
    fullContent: 'O relatório financeiro da Cliente C para o segundo trimestre de 2024 revelou uma diminuição de 5% na receita líquida, surpreendendo os investidores e levando a uma desvalorização de 3% nas ações da empresa. A gerência atribui a queda ao aumento dos custos de matéria-prima e à desaceleração do mercado global. Planos de reestruturação e corte de custos foram anunciados, mas o mercado reagiu com ceticismo. A empresa busca reverter a situação nos próximos trimestres.',
  },
  {
    id: '6',
    title: 'Seleção Nacional de Esportes Garante Vitória no Campeonato',
    summary: 'A seleção nacional conquistou o título do campeonato após uma emocionante partida final, desencadeando celebrações em todo o país.',
    imageUrl: 'https://picsum.photos/600/400?random=6',
    source: 'Mundo Esportivo',
    date: '2024-07-15T20:00:00Z',
    journalist: 'Miguel Rocha',
    category: NewsCategory.SPORTS,
    client: 'Seleções Esportivas', // Novo cliente
    sentiment: Sentiment.UNCLASSIFIED,
    link: 'https://example.com/championship-victory',
    fullContent: 'Em um jogo eletrizante que manteve os torcedores na ponta da cadeira, a Seleção Nacional de Futebol sagrou-se campeã, vencendo por 2 a 1 na prorrogação. O gol da vitória foi marcado nos minutos finais, gerando euforia nacional. Milhares de pessoas saíram às ruas para celebrar o feito histórico. O técnico e os jogadores foram ovacionados pela performance e dedicação durante todo o torneio.',
  },
  {
    id: '7',
    title: 'Pesquisa Médica Avançada Promete Novo Tratamento',
    summary: 'Pesquisadores publicaram descobertas sobre um novo tratamento médico que mostra resultados promissores para uma doença crônica.',
    imageUrl: 'https://picsum.photos/600/400?random=7',
    source: 'Jornal da Saúde',
    date: '2024-07-14T13:00:00Z',
    journalist: 'Emília Mendes',
    category: NewsCategory.HEALTH,
    client: 'Pesquisa Médica', // Novo cliente
    sentiment: Sentiment.UNCLASSIFIED,
    link: 'https://example.com/medical-research',
    fullContent: 'Uma equipe de cientistas da Universidade Federal, em parceria com um laboratório internacional, anunciou o desenvolvimento de uma molécula inovadora que pode ser a base para um tratamento eficaz contra a Doença X, uma condição que afeta milhões. Testes preliminares em laboratório e em pequenos grupos de pacientes mostraram uma redução significativa dos sintomas e uma melhora na qualidade de vida. A comunidade médica está otimista, mas ressalta que mais estudos e ensaios clínicos em larga escala são necessários antes da aprovação final.',
  },
  {
    id: '8',
    title: 'Gigante da Tecnologia Revela Processador de IA de Próxima Geração',
    summary: 'Uma empresa líder em tecnologia apresentou seu mais recente processador de IA, estabelecendo novos padrões para desempenho e eficiência.',
    imageUrl: 'https://picsum.photos/600/400?random=8',
    source: 'Hub de Gadgets',
    date: '2024-07-13T10:45:00Z',
    journalist: 'Davi Luiz',
    category: NewsCategory.TECHNOLOGY,
    client: 'Empresas de Tecnologia', // Novo cliente
    sentiment: Sentiment.UNCLASSIFIED,
    link: 'https://example.com/ai-processor',
    fullContent: 'A GlobalTech Corporation, conhecida por suas inovações em hardware, lançou o "QuantumMind", seu mais novo processador de inteligência artificial. Com arquitetura neural avançada e capacidade de processamento paralelo, o chip promete acelerar drasticamente tarefas de aprendizado de máquina e processamento de dados. A empresa afirma que o QuantumMind será fundamental para a próxima geração de dispositivos inteligentes e sistemas autônomos. A notícia impulsionou as ações da GlobalTech e gerou grande expectativa no mercado de tecnologia.',
  },
  {
    id: '9',
    title: 'Líderes Globais Discutem Mudanças Climáticas em Cúpula',
    summary: 'Líderes mundiais se reuniram para abordar questões urgentes de mudanças climáticas, propondo novas estratégias para proteção ambiental.',
    imageUrl: 'https://picsum.photos/600/400?random=9',
    source: 'Assuntos Mundiais',
    date: '2024-07-12T15:20:00Z',
    journalist: 'Olívia Silva',
    category: NewsCategory.ENVIRONMENT, // Categoria modificada
    client: 'Organizações Globais', // Novo cliente
    sentiment: Sentiment.UNCLASSIFIED,
    link: 'https://example.com/climate-summit',
    fullContent: 'A Cúpula Global do Clima, realizada em Paris, reuniu chefes de estado para discutir metas mais ambiciosas de redução de emissões e estratégias de adaptação. Embora um novo acordo tenha sido assinado, grupos ambientalistas expressaram desapontamento com a lentidão das ações e a falta de compromissos concretos de algumas nações. As negociações foram tensas, mas a declaração final reforça a necessidade de cooperação internacional para enfrentar a crise climática. A comunidade científica continua a alertar sobre a urgência da situação.',
  },
  {
    id: '10',
    title: 'Exposição de Arte Atrai Recorde de Público',
    summary: 'Uma nova exposição de arte com artistas contemporâneos atraiu um número sem precedentes de visitantes desde sua abertura.',
    imageUrl: 'https://picsum.photos/600/400?random=10',
    source: 'Batida da Arte',
    date: '2024-07-11T12:00:00Z',
    journalist: 'Pedro Santos',
    category: NewsCategory.CULTURE, // Categoria modificada
    client: 'Instituições Culturais', // Novo cliente
    sentiment: Sentiment.UNCLASSIFIED,
    link: 'https://example.com/art-exhibition',
    fullContent: 'A exposição "Vanguardas Contemporâneas", no Museu de Arte Moderna, superou todas as expectativas de público, registrando mais de 50 mil visitantes na primeira semana. A mostra, que reúne obras de artistas emergentes e consagrados, tem sido elogiada pela crítica pela sua curadoria ousada e pela capacidade de provocar reflexão sobre os rumos da arte moderna. Filas se formam diariamente para apreciar as instalações interativas e as pinturas abstratas. Um sucesso para o cenário cultural da cidade.',
  },
];

export const MOCK_SOCIAL_MEDIA_POSTS: SocialMediaPost[] = [
  {
    id: 'sm1',
    platform: SocialMediaPlatform.TWITTER,
    content: 'Grande notícia! A Cliente A acaba de anunciar uma aquisição que vai agitar o mercado de tecnologia! 🚀 #ClienteA #Tecnologia #Inovação',
    date: '2024-07-20T11:00:00Z',
    client: 'Cliente A',
    sentiment: Sentiment.UNCLASSIFIED,
    likes: 1500,
    comments: 230,
    shares: 450,
    link: 'https://twitter.com/example/status/sm1',
  },
  {
    id: 'sm2',
    platform: SocialMediaPlatform.FACEBOOK,
    content: 'Compartilhando a nova política de infraestrutura do governo. Muitos debates nas redes sociais! Qual a sua opinião? #Governo #PolíticaPública',
    date: '2024-07-19T15:00:00Z',
    client: 'Instituições Públicas',
    sentiment: Sentiment.UNCLASSIFIED,
    likes: 800,
    comments: 400,
    shares: 120,
    link: 'https://facebook.com/example/post/sm2',
  },
  {
    id: 'sm3',
    platform: SocialMediaPlatform.LINKEDIN,
    content: 'Orgulho de anunciar o avanço da Cliente B em energia solar! Rumo a um futuro mais verde e sustentável. #Sustentabilidade #ClienteB #InovaçãoVerde',
    date: '2024-07-18T10:00:00Z',
    client: 'Cliente B',
    sentiment: Sentiment.UNCLASSIFIED,
    likes: 3000,
    comments: 150,
    shares: 600,
    link: 'https://linkedin.com/example/post/sm3',
  },
  {
    id: 'sm4',
    platform: SocialMediaPlatform.INSTAGRAM,
    content: 'Celebrando a Personalidade Local pela sua incrível dedicação à comunidade! Inspirador! ✨ #Comunidade #HeroiLocal',
    date: '2024-07-17T12:00:00Z',
    client: 'Personalidades',
    sentiment: Sentiment.UNCLASSIFIED,
    likes: 5000,
    comments: 100,
    shares: 50,
    link: 'https://instagram.com/example/post/sm4',
  },
  {
    id: 'sm5',
    platform: SocialMediaPlatform.TWITTER,
    content: 'Resultados do Q2 da Cliente C deixam investidores apreensivos. O mercado reage com cautela. #ClienteC #MercadoFinanceiro',
    date: '2024-07-16T17:00:00Z',
    client: 'Cliente C',
    sentiment: Sentiment.UNCLASSIFIED,
    likes: 300,
    comments: 80,
    shares: 100,
    link: 'https://twitter.com/example/status/sm5',
  },
  {
    id: 'sm6',
    platform: SocialMediaPlatform.FACEBOOK,
    content: 'VITÓRIA! Nossa seleção é CAMPEÃ! Que orgulho! 🏆⚽️ #Futebol #Campeões',
    date: '2024-07-15T21:00:00Z',
    client: 'Seleções Esportivas',
    sentiment: Sentiment.UNCLASSIFIED,
    likes: 10000,
    comments: 2000,
    shares: 5000,
    link: 'https://facebook.com/example/post/sm6',
  },
  {
    id: 'sm7',
    platform: SocialMediaPlatform.LINKEDIN,
    content: 'Novas perspectivas de tratamento para doenças crônicas! Um passo gigante para a saúde global. #PesquisaMédica #Saúde',
    date: '2024-07-14T14:00:00Z',
    client: 'Pesquisa Médica',
    sentiment: Sentiment.UNCLASSIFIED,
    likes: 2500,
    comments: 120,
    shares: 300,
    link: 'https://linkedin.com/example/post/sm7',
  },
  {
    id: 'sm8',
    platform: SocialMediaPlatform.TWITTER,
    content: 'O futuro da IA chegou! GlobalTech anuncia processador revolucionário. 🤯 #IA #Tecnologia #GlobalTech',
    date: '2024-07-13T11:00:00Z',
    client: 'Empresas de Tecnologia',
    sentiment: Sentiment.UNCLASSIFIED,
    likes: 1800,
    comments: 300,
    shares: 700,
    link: 'https://twitter.com/example/status/sm8',
  },
  {
    id: 'sm9',
    platform: SocialMediaPlatform.FACEBOOK,
    content: 'Discussões importantes na Cúpula do Clima. O que você espera dos líderes mundiais? #MudançasClimáticas #MeioAmbiente',
    date: '2024-07-12T16:00:00Z',
    client: 'Organizações Globais',
    sentiment: Sentiment.UNCLASSIFIED,
    likes: 700,
    comments: 250,
    shares: 90,
    link: 'https://facebook.com/example/post/sm9',
  },
  {
    id: 'sm10',
    platform: SocialMediaPlatform.INSTAGRAM,
    content: 'Recorde de público na exposição "Vanguardas Contemporâneas"! Arte que inspira! 🖼️✨ #Arte #Cultura',
    date: '2024-07-11T13:00:00Z',
    client: 'Instituições Culturais',
    sentiment: Sentiment.UNCLASSIFIED,
    likes: 4500,
    comments: 80,
    shares: 40,
    link: 'https://instagram.com/example/post/sm10',
  },
];
